version: "3.9"

services:

  nginx:
    container_name: nginx
    build: ./requirements/nginx
    image: nginx
    networks:
      - net
    ports:
      - "443:443"
    volumes:
      - wp_volume:/var/wordpress
    restart: unless-stopped
    depends_on:
      - wordpress
    env_file:
      - .env

  wordpress:
    container_name: wordpress
    build: ./requirements/wordpress
    image: wordpress
    networks:
      - net
    ports:
      - "9000:9000"
    volumes:
      - wp_volume:/var/wordpress
    restart: unless-stopped
    depends_on:
      - mariadb
    env_file:
      - .env

  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb
    image: mariadb
    networks:
      - net
    ports:
      - "3306:3306"
    volumes:
      - db_volume:/var/lib/mysql
    restart: unless-stopped
    env_file:
      - .env

  redis:
    container_name: redis
    build: ./requirements/redis
    image: redis
    networks:
      - net
    ports:
      - "6379:6379"
    restart: unless-stopped
    env_file:
      - .env

  ftp:
    container_name: ftp
    build:
      context: ./requirements/ftp
      args:
            FTP_USER: ${FTP_USER}
            FTP_PASSWORD: ${FTP_PASSWORD}
    image: ftp
    networks:
      - net
    ports:
      - "20:20"
      - "21:21"
      - "1024-1048:1024-1048"
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - wp_volume:/var/wordpress

  portfolio:
    container_name: portfolio
    build: ./requirements/portfolio
    image: portfolio
    networks:
      - net
    ports:
      - "5000:5000"
    restart: unless-stopped
    env_file:
      - .env
  
  portainer:
    container_name: portainer
    build: ./requirements/portainer
    image: portainer
    networks:
      - net
    ports:
      - "7000:7000"
    restart: unless-stopped
    volumes:
      - pt_volume:/data
      - /var/run/docker.sock:/var/run/docker.sock
    

networks:
  net:
volumes:
  wp_volume:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: /home/$USER/data/wp_data
  db_volume:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: /home/$USER/data/mysql_data
  pt_volume:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: /home/$USER/data/portainer_data