version: "3.9"

services:

  nginx:
    build: ./requirements/nginx
    networks:
      - net
    ports:
      - "443:443"
    volumes:
      - wp_volume:/var/wordpress
    restart: unless-stopped
    depends_on:
      - wordpress
    env_file:
      - .env

  wordpress:
    build: ./requirements/wordpress
    networks:
      - net
    ports:
      - "9000:9000"
    volumes:
      - wp_volume:/var/wordpress
    restart: unless-stopped
    depends_on:
      - mariadb
    env_file:
      - .env

  mariadb:
    build: ./requirements/mariadb
    networks:
      - net
    ports:
      - "3306:3306"
    volumes:
      - db_volume:/var/lib/mysql
    restart: unless-stopped
    env_file:
      - .env

networks:
  net:
volumes:
  wp_volume:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: /home/$USER/data/wp_data
  db_volume:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: /home/$USER/data/mysql_data
